# Generated by Django 3.2.4 on 2021-06-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bob',
            name='contribution',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('post', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('Bob Moment', 'Bob Moment'), ('Tech', 'Tech')], max_length=200, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bob')),
            ],
        ),
    ]
