# Generated by Django 3.2.4 on 2021-06-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210616_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='bob',
            name='contribution',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bob',
            name='title',
            field=models.CharField(choices=[('Godbob', 'Godbob'), ('Archbob', 'Archbob'), ('Masterbob', 'Masterbob'), ('Newbob', 'Newbob')], max_length=200, null=True),
        ),
    ]
