# Generated by Django 3.2.4 on 2021-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210617_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bob',
            name='title',
            field=models.CharField(choices=[('Godbob', 'Godbob'), ('Archbob', 'Archbob'), ('Masterbob', 'Masterbob'), ('Newbob', 'Newbob'), ('Failbob', 'Failbob')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='base.Tag'),
        ),
    ]
