# Generated by Django 3.2.4 on 2021-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210618_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='bob',
            name='title',
            field=models.CharField(choices=[('Godbob', 'Godbob'), ('Archbob', 'Archbob'), ('Masterbob', 'Masterbob'), ('Newbob', 'Newbob'), ('Failbob', 'Failbob'), ('Lesbob', 'Lesbob')], max_length=200, null=True),
        ),
    ]
